const image = (slug) => `/exercise-images/${slug}.svg`

export const exerciseLibrary = [
  {
    id: 'push-up',
    names: { en: 'Push-Up', fr: 'Pompe', ar: 'ضغط' },
    muscleGroup: 'chest',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelBeginner',
    image: '/exercise-images/Push-Up.jpeg',
    reps: '3 x 12',
    rest: '45 sec',
    notes: {
      en: 'Keep your core braced and elbows slightly tucked.',
      fr: 'Gardez le tronc gainé et les coudes legerement rentres.',
      ar: 'شد الجذع وابق المرفقين قريبين قليلا من الجسم.',
    },
  },
  {
    id: 'bench-press',
    names: { en: 'Bench Press', fr: 'Developpe couche', ar: 'بنش برس' },
    muscleGroup: 'chest',
    location: 'gym',
    equipment: { en: 'Barbell', fr: 'Barre', ar: 'بار' },
    level: 'levelIntermediate',
    image: '/exercise-images/bench-Press.jpeg',
    reps: '4 x 6-8',
    rest: '90 sec',
    notes: {
      en: 'Drive your feet into the floor and control the bar path.',
      fr: 'Poussez les pieds dans le sol et controlez la trajectoire de la barre.',
      ar: 'ادفع القدمين في الأرض وتحكم في مسار البار.',
    },
  },
  {
    id: 'incline-dumbbell-press',
    names: { en: 'Incline Dumbbell Press', fr: 'Developpe incline halteres', ar: 'بنش مائل بالدامبل' },
    muscleGroup: 'chest',
    location: 'gym',
    equipment: { en: 'Dumbbells', fr: 'Halteres', ar: 'دامبل' },
    level: 'levelIntermediate',
    image: '/exercise-images/incline-dumbbell-press.jpeg'
    ,
    reps: '3 x 10',
    rest: '75 sec',
    notes: {
      en: 'Angle the bench slightly and squeeze at the top.',
      fr: 'Inclinez legerement le banc et contractez en haut.',
      ar: 'اجعل ميل المقعد خفيفا واضغط في أعلى الحركة.',
    },
  },
  {
    id: 'pull-up',
    names: { en: 'Pull-Up', fr: 'Traction', ar: 'سحب علوي' },
    muscleGroup: 'back',
    location: 'gym',
    equipment: { en: 'Pull-Up Bar', fr: 'Barre de traction', ar: 'بار العقلة' },
    level: 'levelIntermediate',
    image: '/exercise-images/pull-up.jpeg',
    reps: '4 x 6-10',
    rest: '90 sec',
    notes: {
      en: 'Lead with the chest and avoid swinging.',
      fr: 'Menez avec la poitrine et evitez l elan.',
      ar: 'ابدأ بالصدر وتجنب التأرجح.',
    },
  },
  {
    id: 'one-arm-row',
    names: { en: 'One-Arm Dumbbell Row', fr: 'Rowing un bras haltere', ar: 'تجديف دامبل بذراع واحدة' },
    muscleGroup: 'back',
    location: 'gym',
    equipment: { en: 'Dumbbell', fr: 'Haltere', ar: 'دامبل' },
    level: 'levelBeginner',
    image: '/exercise-images/one-arm-row.jpeg',
    reps: '3 x 10 each side',
    rest: '60 sec',
    notes: {
      en: 'Pull the elbow toward the hip and keep the spine neutral.',
      fr: 'Tirez le coude vers la hanche et gardez la colonne neutre.',
      ar: 'اسحب المرفق نحو الورك مع إبقاء الظهر محايدا.',
    },
  },
  {
    id: 'superman-hold',
    names: { en: 'Superman Hold', fr: 'Superman hold', ar: 'سوبرمان ثابت' },
    muscleGroup: 'back',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelBeginner',
    image: '/exercise-images/superman-hold.jpeg',
    reps: '3 x 30 sec',
    rest: '30 sec',
    notes: {
      en: 'Lift chest and legs together without overextending the neck.',
      fr: 'Levez la poitrine et les jambes sans casser la nuque.',
      ar: 'ارفع الصدر والساقين معا دون ضغط زائد على الرقبة.',
    },
  },
  {
    id: 'shoulder-press',
    names: { en: 'Shoulder Press', fr: 'Developpe epaules', ar: 'ضغط كتف' },
    muscleGroup: 'shoulders',
    location: 'gym',
    equipment: { en: 'Dumbbells', fr: 'Halteres', ar: 'دامبل' },
    level: 'levelIntermediate',
    image: '/exercise-images/shoulder-press.jpeg',
    reps: '4 x 8',
    rest: '75 sec',
    notes: {
      en: 'Stack wrists over elbows and avoid leaning back.',
      fr: 'Gardez les poignets au-dessus des coudes et evitez de vous cambrer.',
      ar: 'اجعل المعصمين فوق المرفقين وتجنب إرجاع الظهر.',
    },
  },
  {
    id: 'pike-push-up',
    names: { en: 'Pike Push-Up', fr: 'Pompe piquee', ar: 'ضغط بايك' },
    muscleGroup: 'shoulders',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelIntermediate',
    image: '/exercise-images/pike-push-up.jpeg',
    reps: '3 x 10',
    rest: '45 sec',
    notes: {
      en: 'Shift weight forward to bias the shoulders.',
      fr: 'Avancez le poids du corps pour cibler davantage les epaules.',
      ar: 'حرك الوزن للأمام لزيادة تركيز التمرين على الكتفين.',
    },
  },
  {
    id: 'lateral-raise',
    names: { en: 'Lateral Raise', fr: 'Elevation laterale', ar: 'رفرفة جانبية' },
    muscleGroup: 'shoulders',
    location: 'gym',
    equipment: { en: 'Dumbbells', fr: 'Halteres', ar: 'دامبل' },
    level: 'levelBeginner',
    image: '/exercise-images/lateral-raise.jpeg',
    reps: '3 x 12-15',
    rest: '45 sec',
    notes: {
      en: 'Lift to shoulder height with soft elbows.',
      fr: 'Montez jusqu a la hauteur des epaules avec des coudes souples.',
      ar: 'ارفع حتى مستوى الكتف مع بقاء المرفقين مرتاحين.',
    },
  },
  {
    id: 'bicep-curl',
    names: { en: 'Bicep Curl', fr: 'Curl biceps', ar: 'بايسبس كورل' },
    muscleGroup: 'arms',
    location: 'gym',
    equipment: { en: 'Dumbbells', fr: 'Halteres', ar: 'دامبل' },
    level: 'levelBeginner',
    image: '/exercise-images/bicep-curl.jpeg',
    reps: '3 x 12',
    rest: '45 sec',
    notes: {
      en: 'Keep elbows pinned and move only at the elbow.',
      fr: 'Gardez les coudes fixes et bougez seulement l avant-bras.',
      ar: 'ثبت المرفقين وحرك الساعد فقط.',
    },
  },
  {
    id: 'chair-dip',
    names: { en: 'Chair Dip', fr: 'Dips sur chaise', ar: 'ديبس على كرسي' },
    muscleGroup: 'arms',
    location: 'home',
    equipment: { en: 'Chair', fr: 'Chaise', ar: 'كرسي' },
    level: 'levelBeginner',
    image: '/exercise-images/chair-dip.jpeg',
    reps: '3 x 12',
    rest: '45 sec',
    notes: {
      en: 'Lower with control and keep shoulders down.',
      fr: 'Descendez avec controle et gardez les epaules basses.',
      ar: 'انزل بتحكم مع إبقاء الكتفين منخفضين.',
    },
  },
  {
    id: 'tricep-pushdown',
    names: { en: 'Tricep Pushdown', fr: 'Extension triceps poulie', ar: 'ترايسبس بوش داون' },
    muscleGroup: 'arms',
    location: 'gym',
    equipment: { en: 'Cable Machine', fr: 'Poulie', ar: 'آلة كيبل' },
    level: 'levelBeginner',
    image: '/exercise-images/tricep-pushdown.jpeg',
    reps: '3 x 12',
    rest: '45 sec',
    notes: {
      en: 'Lock elbows at your sides and fully extend.',
      fr: 'Gardez les coudes serres au corps et tendez completement.',
      ar: 'ثبت المرفقين بجانب الجسم ومد الذراع بالكامل.',
    },
  },
  {
    id: 'squat',
    names: { en: 'Squat', fr: 'Squat', ar: 'سكوات' },
    muscleGroup: 'legs',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelBeginner',
    image: '/exercise-images/squat.jpeg',
    reps: '4 x 15',
    rest: '60 sec',
    notes: {
      en: 'Sit down and back while keeping the chest tall.',
      fr: 'Asseyez-vous en arriere en gardant la poitrine haute.',
      ar: 'انزل للخلف مع إبقاء الصدر مرفوعا.',
    },
  },
  {
    id: 'barbell-squat',
    names: { en: 'Barbell Back Squat', fr: 'Squat arriere barre', ar: 'سكوات خلفي بالبار' },
    muscleGroup: 'legs',
    location: 'gym',
    equipment: { en: 'Barbell', fr: 'Barre', ar: 'بار' },
    level: 'levelAdvanced',
    image: '/exercise-images/barbell-squat.jpeg',
    reps: '5 x 5',
    rest: '120 sec',
    notes: {
      en: 'Brace hard and keep the bar balanced over midfoot.',
      fr: 'Gainage fort et barre equilibree au-dessus du milieu du pied.',
      ar: 'شد الجذع بقوة وابق البار فوق منتصف القدم.',
    },
  },
  {
    id: 'romanian-deadlift',
    names: { en: 'Romanian Deadlift', fr: 'Souleve de terre roumain', ar: 'رومانيان ديدليفت' },
    muscleGroup: 'glutes',
    location: 'gym',
    equipment: { en: 'Barbell', fr: 'Barre', ar: 'بار' },
    level: 'levelIntermediate',
    image: '/exercise-images/romanian-deadlift.jpeg',
    reps: '4 x 8',
    rest: '90 sec',
    notes: {
      en: 'Push the hips back and keep the bar close to the body.',
      fr: 'Reculez les hanches et gardez la barre proche du corps.',
      ar: 'ادفع الوركين للخلف وأبق البار قريبا من الجسم.',
    },
  },
  {
    id: 'glute-bridge',
    names: { en: 'Glute Bridge', fr: 'Pont fessier', ar: 'جسر الأرداف' },
    muscleGroup: 'glutes',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelBeginner',
    image: '/exercise-images/glute-bridge.jpeg',
    reps: '4 x 15',
    rest: '45 sec',
    notes: {
      en: 'Drive through the heels and pause at the top.',
      fr: 'Poussez dans les talons et marquez une pause en haut.',
      ar: 'ادفع بالكعبين وتوقف لحظة في أعلى الحركة.',
    },
  },
  {
    id: 'plank',
    names: { en: 'Plank', fr: 'Planche', ar: 'بلانك' },
    muscleGroup: 'core',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelBeginner',
    image: '/exercise-images/plank.jpeg',
    reps: '3 x 45 sec',
    rest: '30 sec',
    notes: {
      en: 'Pull ribs down and squeeze glutes.',
      fr: 'Rentrez les cotes et serrez les fessiers.',
      ar: 'اسحب الأضلاع للداخل واشد الأرداف.',
    },
  },
  {
    id: 'dead-bug',
    names: { en: 'Dead Bug', fr: 'Dead bug', ar: 'ديد باغ' },
    muscleGroup: 'core',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelBeginner',
    image: '/exercise-images/dead-bug.jpeg',
    reps: '3 x 12 each side',
    rest: '30 sec',
    notes: {
      en: 'Keep the lower back gently pressed into the floor.',
      fr: 'Gardez le bas du dos legerement plaque au sol.',
      ar: 'ابق أسفل الظهر ملاصقا للأرض بخفة.',
    },
  },
  {
    id: 'hanging-knee-raise',
    names: { en: 'Hanging Knee Raise', fr: 'Releve de genoux suspendu', ar: 'رفع الركبتين معلقا' },
    muscleGroup: 'core',
    location: 'gym',
    equipment: { en: 'Pull-Up Bar', fr: 'Barre de traction', ar: 'بار العقلة' },
    level: 'levelIntermediate',
    image: '/exercise-images/hanging-knee-raise.jpeg',
    reps: '3 x 12',
    rest: '45 sec',
    notes: {
      en: 'Lift the knees with control instead of swinging.',
      fr: 'Montez les genoux avec controle sans balancer.',
      ar: 'ارفع الركبتين بتحكم من دون تأرجح.',
    },
  },
  {
    id: 'burpee',
    names: { en: 'Burpee', fr: 'Burpee', ar: 'بوربي' },
    muscleGroup: 'fullBody',
    location: 'home',
    equipment: { en: 'Bodyweight', fr: 'Poids du corps', ar: 'وزن الجسم' },
    level: 'levelAdvanced',
    image: '/exercise-images/burpee.jpeg',
    reps: '4 x 10',
    rest: '45 sec',
    notes: {
      en: 'Keep the pace smooth and land softly.',
      fr: 'Gardez un rythme fluide et atterrissez en douceur.',
      ar: 'حافظ على إيقاع سلس واهبط بخفة.',
    },
  },
  {
    id: 'kettlebell-swing',
    names: { en: 'Kettlebell Swing', fr: 'Swing kettlebell', ar: 'كيتلبيل سوينغ' },
    muscleGroup: 'fullBody',
    location: 'gym',
    equipment: { en: 'Kettlebell', fr: 'Kettlebell', ar: 'كيتلبيل' },
    level: 'levelIntermediate',
    image: '/exercise-images/kettlebell-swing.jpeg',
    reps: '4 x 15',
    rest: '45 sec',
    notes: {
      en: 'Hinge at the hips and let the bell float.',
      fr: 'Charniere aux hanches et laissez la kettlebell flotter.',
      ar: 'اثن عند الورك واترك الكيتلبيل يتحرك بسلاسة.',
    },
  },
]

export const starterWorkouts = [
  {
    id: 'starter-upper',
    names: { en: 'Upper Body Power', fr: 'Puissance haut du corps', ar: 'قوة الجزء العلوي' },
    duration: 45,
    level: 'levelIntermediate',
    calories: 320,
    color: '#ff4d6d',
    location: 'gym',
    focus: 'chest',
    exercises: ['bench-press', 'pull-up', 'shoulder-press', 'bicep-curl'],
  },
  {
    id: 'starter-lower',
    names: { en: 'Lower Body Blast', fr: 'Bas du corps intense', ar: 'دفعة الجزء السفلي' },
    duration: 40,
    level: 'levelBeginner',
    calories: 280,
    color: '#00dfa0',
    location: 'home',
    focus: 'legs',
    exercises: ['squat', 'glute-bridge', 'plank'],
  },
  {
    id: 'starter-core',
    names: { en: 'Core Control', fr: 'Controle du centre', ar: 'تحكم الكور' },
    duration: 30,
    level: 'levelAll',
    calories: 210,
    color: '#ffad35',
    location: 'home',
    focus: 'core',
    exercises: ['plank', 'dead-bug', 'burpee'],
  },
  {
    id: 'starter-full',
    names: { en: 'Full Body Engine', fr: 'Moteur corps entier', ar: 'قوة الجسم كامل' },
    duration: 35,
    level: 'levelAdvanced',
    calories: 420,
    color: '#5080f0',
    location: 'gym',
    focus: 'fullBody',
    exercises: ['barbell-squat', 'romanian-deadlift', 'bench-press', 'kettlebell-swing'],
  },
]

export const muscleGroups = ['all', 'chest', 'back', 'shoulders', 'arms', 'legs', 'glutes', 'core', 'fullBody']
